### ISSUE TITLE
none

### ISSUE THREAD

**Issue by unverciftci** [billyc/keyboard#1]

**Comment by billyc** [comment]
Ok... so a little more detail would help me to troubleshoot your problem!

Are you on Windows or Linux?

You said it's installed correctly, so can you now choose it? On my PC I can use the Windows key + Space bar, or click on the "EN" icon by the system clock in the taskbar, to switch keyboards.

**Comment by unverciftci** [comment]
I am on Windows. The problem is I can't make work. For instance when I press right alt + u, it responds ú.
